services:

  spark:
    image: apache/spark:3.5.0
    container_name: spark
    volumes:
      - ../:/app
    command: sleep infinity

  airflow:
    image: apache/airflow:2.8.3
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: mohammed.genclays@gmail.com

    volumes:
      - ../airflow:/opt/airflow/dags
    command: standalone

  ui:
    image: python:3.10
    container_name: ui
    volumes:
      - ../ui:/ui
    working_dir: /ui
    command: bash -c "pip install streamlit && streamlit run app.py"
    ports:
      - "8501:8501"