pipelines:
- pii_columns:
  - name
  pipeline_name: employee_pipeline
  scd_type: 2
  sensitive_columns:
  - salary
  source:
    file_type: csv
    path: gs://genclays/raw/employee.csv
  staging_table: staging.employee
  target_table: target.employee_dim
- pipeline_name: employee_pipeline2
  scd_type: 2
  source:
    file_type: csv
    path: gs://genclays/raw/employee.csv
  staging_table: staging.employee_pipeline2
  target_table: target.employee_pipeline2_dim
